site_name: FastAPI Login
theme:
  name: material
  palette:
    primary: light green
    accent: orange

nav:
  - About: index.md
  - installation.md
  - setup.md
  - usage.md
  - advanced_usage.md


markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs